# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.20.10"

   config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install -y php5 php5-cli php5-mcrypt php5-cgi libapache2-mod-php5
     sudo apt-get install -y apache2
     sudo apt-get install -y git
     sudo debconf-set-selections <<< 'mysql-server-5.5 mysql-server/root_password password hello_world'
     sudo debconf-set-selections <<< 'mysql-server-5.5 mysql-server/root_password_again password hello_world'
     sudo apt-get install -y mysql-server libapache2-mod-auth-mysql php5-mysql
     sudo chmod a+w /usr/local/bin/
     cd /usr/local/bin/ && curl -sS https://getcomposer.org/installer | php
     sudo service apache2 reload
   SHELL
end